// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzgheranvylzmnakrjxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Z2hlcmFudnlsem1uYWtyanhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTc1NzIsImV4cCI6MjA1Nzc5MzU3Mn0.RPws1fuMQt3TF-S3CB5o3_8nUCsUi_x_RrrgfLdq7J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);